# This file was generated by GoReleaser. DO NOT EDIT.
class Gsh < Formula
  desc "A command line tool to use GSH"
  homepage "https://github.com/globocom/gsh"
  url "https://github.com/globocom/gsh/releases/download/v0.1.3/gsh-darwin-amd64.tar.gz"
  sha256 "b14caf6eaf63f12ab16455cc4c802c2c4d4edc4b3826bdfc5298c3e7b9bb8b93"
  version "0.1.3"
  depends_on "openssh"

  def install
    bin.install "gsh"
  end

  devel do
    depends_on "go"
    depends_on "dep"
    url "https://github.com/globocom/gsh.git",
      :tag      => "v0.1.3",
      :revision => "f63c8b7f5200364e21d67769c9cc5f2d4b95e748"

    ENV["GOPATH"] = buildpath
    ENV["CGO_ENABLED"] = "1"
    (buildpath/"src/github.com/globocom/gsh").install buildpath.children
    cd "src/github.com/globocom/gsh" do
      system "dep", "ensure"
      system "go", "build", "-o", "gsh", "./cli/main.go"
      bin.install "gsh"
    end
  end
end